pipeline{
    agent none
    environment{
        TEST="test_value"
        TEST1="test_value1"
    }
    stages{
        stage ('Build'){
            agent {
                label 'Slave1'
            }
            steps{
                  sh 'sleep 5'
            }
        }
    
        stage ('Test'){
            agent {
                label 'Slave2'
            }
            steps{
                  sh '''
                  #!/bin/bash
                  ls -lrt
                  sleep 5
                  '''
            }
        }

    }
}
