pipeline{
    agent any

    stages{
        stage ('Checkout'){
                steps{
                   checkout([$class: 'GitSCM',
                   branches : [[name:'*/master' ]],
                   userRemoteConfigs: [[url: 'https://github.com/Ga135/jenkins_pipeline_java_maven.git'
                 ]] ])
 
                }
            }
       
        stage('Test Multiple')
        {
            parallel{
                stage ('Build'){
                    steps{
                        sh '''
                        ls -lrt
                        '''
                    }
                }
                stage ('Test'){
                    steps{
                            sh '''
                            sleep 1
                            '''   
                    }
                }
            }
        }
        stage ('Deploy'){
            steps{
                  sh '''
                  ls -lrt
                  '''
            }
        }
       
    }
}
